export const GET_USERS_LOADING = 'GET_USERS_LOADING'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_ERROR = 'GET_USERS_ERROR'

export const GET_MESAS_LOADING = 'GET_MESAS_LOADING'
export const GET_MESAS_SUCCESS = 'GET_MESAS_SUCCESS'
export const GET_MESAS_ERROR = 'GET_MESAS_ERROR'