export const GET_USERS_LOADING = 'GET_USERS_LOADING'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_ERROR = 'GET_USERS_ERROR'

export const GET_MESAS_LOADING = 'GET_MESAS_LOADING'
export const GET_MESAS_SUCCESS = 'GET_MESAS_SUCCESS'
export const GET_MESAS_ERROR = 'GET_MESAS_ERROR'

export const GET_PRODUCTOS_LOADING = 'GET_PRODUCTOS_LOADING'
export const GET_PRODUCTOS_SUCCESS = 'GET_PRODUCTOS_SUCCESS'
export const GET_PRODUCTOS_ERROR = 'GET_PRODUCTOS_ERROR'

export const GET_PROVEEDORES_LOADING = 'GET_PROVEEDORES_LOADING'
export const GET_PROVEEDORES_SUCCESS = 'GET_PROVEEDORES_SUCCESS'
export const GET_PROVEEDORES_ERROR = 'GET_PROVEEDORES_ERROR'

export const GET_PLATOS_LOADING = 'GET_PLATOS_LOADING'
export const GET_PLATOS_SUCCESS = 'GET_PLATOS_SUCCESS'
export const GET_PLATOS_ERROR = 'GET_PLATOS_ERROR'

export const GET_BOLETAS_SUCCESS = 'GET_BOLETAS_SUCCESS'
export const GET_BOLETAS_LOADING = 'GET_BOLETAS_LOADING'
export const GET_BOLETAS_ERROR = 'GET_BOLETAS_ERROR'

export const GET_FACTURAS_SUCCESS = 'GET_FACTURAS_SUCCESS'
export const GET_FACTURAS_LOADING = 'GET_FACTURAS_LOADING'
export const GET_FACTURAS_ERROR = 'GET_FACTURAS_ERROR'

export const GET_PEDIDOSPROV_SUCCESS = 'GET_PEDIDOSPROV_SUCCESS'

export const GET_DETALLEORDS_SUCCESS = 'GET_DETALLEORDS_SUCCESS'

export const GET_ORDENES_SUCCESS = 'GET_ORDENES_SUCCESS'